### ISSUE TITLE
Backup code retrieval not reflecting accurate created date

### ISSUE THREAD

**Issue by hobbitronics** [silinternational/idp-pw-api#212]
Initially discovered in https://github.com/silinternational/idp-profile-ui/issues/24. After investigation it turns out the `https://profile-api.gtis.guru/mfa` call is returning an old `created_utc`.

The problem only occurs when replacing created backup codes, but not when creating new backup codes when none existed. 

```
POST https://profile-api.gtis.guru/mfa {"type":"backupcode"}
``` 
@forevermatt

**Comment by devon-sil** [comment]
@hobbitronics @forevermatt Would either of you verify if this is still an issue?

**Comment by briskt** [comment]
Looks like it was fixed here: https://github.com/silinternational/idp-id-broker/releases/tag/5.2.3
