### ISSUE TITLE
Masking of email domains assumes only two parts

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-pw-api#23]
The code at https://github.com/silinternational/idp-pw-api/blob/develop/application/common/helpers/Utils.php#L174 uses `list()` and `explode()` to separate the email address's domain into parts and mask each one. This assumes a "domain.tld" format, and would probably break for a "sub.domain.tld" domain.

We recently fixed this same issue in another project, so you could either borrow the updated logic from there or, perhaps better, we could start using an external dependency for these sorts of utility functions.

**Comment by Schparky** [comment]
Addressed by #176
