### ISSUE TITLE
Adding a method that already exists behaves a little strangely...maybe.

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-pw-api#34]
When I POST /method with a phone number that already exists, I get a 200 (which is fine in my mind) however doing a PUT on that method id with ANY verification code works.  I might be ok if that was intentional since we can make a semantic argument that it was already verified therefore there's no need to jump through a bunch of hoops on this use case, however I wanted to bring it up to make sure my understanding of the API was clear since having the ability to verify with ANY code seems strange and I don't think a code is actually even sent.  Thanks

**Comment by fillup** [comment]
fixed in commit 8614ed0
