### ISSUE TITLE
When a reset has been validated, should the password should be expired?

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-pw-api#35]
I noticed a scenario I believe warrants a little discussion:  

1. User initiates a reset
2. Validates it
3. While the user is on the "Change password" page, they cancel
4. They are then sent to the profile page with their previous credentials

![image](https://cloud.githubusercontent.com/assets/4412848/16842146/5696b72a-49aa-11e6-95c1-ca937f4c01fd.png)

Possibilities:
1. Remove the "cancel" option on the UI (however there's still the possibility the user could leave without changing his/her password).
2. Perform some API call when user cancels.
3. API creates some state on the db when a user validates the reset.

**Comment by fillup** [comment]
Lets:

1. remove the cancel button
2. On navigate away present confirm dialog
3. On confirm leave fire off API call to /auth/logout
4. Flush local storage of client_id and access_token

**Comment by wcjr** [comment]
moved to https://github.com/silinternational/idp-pw-ui/issues/11
