### ISSUE TITLE
Missing CORS header on 401

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-pw-api#38]
![image](https://cloud.githubusercontent.com/assets/4412848/17001217/16c210e2-4e94-11e6-9c07-6993a0537033.png)

Can we ensure the header is present on those as well?

**Comment by fillup** [comment]
Negative. If you're not logged on requests to resources that require login, it never gets to the CORS filter so the headers don't get added.

**Comment by wcjr** [comment]
ok, thanks for taking a look
